# https://github.com/sid88in/serverless-appsync-plugin

service: potluck-appsync

provider:
  name: aws
  runtime: nodejs12.x
  profile: potluck
  stackName: PotluckAppSyncCloudFormationStack-${self:custom.env}
  region: ${opt:region}
  endpointType: regional
  tags:
    Potluck: Potluck

layers:
  awsAppsyncLayer:
    path: layers/awsAppsyncLayer/dist/
    name: AwsAppsyncLayer-${self:custom.env}
    retain: true
    description: Node module layer for aws-appsync since its 10mb
    compatibleRuntimes:
      - nodejs12.x

plugins:
  - serverless-appsync-plugin

resources:
  # DynamoDB tables
  - ${file(resources/dynamodb-table.yml)}

functions:
  - ${file(resources/lambda.yml)}

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Set the table name here so we can use it while testing locally
  env: ${self:custom.stage}
  # region
  region: ${opt:region}
  defaultUserPoolId: us-east-1_3NAAjhsu9
  userPoolId: us-east-1_3NAAjhsu9
  # cognito client id
  clientId: 33kpeg3vkhc09qrvummudiiqae

  # appsync plugin configuration
  appSync: ${file(resources/app-sync.yml)}
